name: mobile_megajr_grupo3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: "^0.14.3"


flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/logo.png"
  ios: true
  remove_alpha_ios: true
  android: "laucher_icon"
  adaptative_icon_background: "#FFFFFF"
  adaptative_icon_foreground: "assets/logo_sem_fundo.png"
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter:
  uses-material-design: true

  assets:
    - assets/pato.png
    - assets/logo.png
    - assets/splash.png
