name: mobile_megajr_grupo3
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: "^0.14.3"
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  reorderable_grid_view: ^2.2.8
  firebase_core: ^2.27.0 # Para inicializar o Firebase
  firebase_auth: ^4.17.8 # Para autenticação de e-mail/senha
  google_sign_in: ^6.2.1 # Para login com Google
  http: ^1.2.1 # Para fazer requisições HTTP (chamadas de API)
  provider: ^6.0.5

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/logo.png"
  ios: true
  remove_alpha_ios: true
  android: "laucher_icon"
  adaptative_icon_background: "#FFFFFF"
  adaptative_icon_foreground: "assets/logo_sem_fundo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pato.png
    - assets/splash-pato.png
    - assets/googleicon.png
    - assets/gif-pato.gif
    - assets/pato-triste.png
