name: mobile_megajr_grupo3
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: "^0.14.3"
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  reorderable_grid_view: ^2.2.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  http: ^1.2.1
  provider: ^6.0.5
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.4
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.3.1

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/logo.png"
  ios: true
  remove_alpha_ios: true
  android: "laucher_icon"
  adaptative_icon_background: "#FFFFFF"
  adaptative_icon_foreground: "assets/logo_sem_fundo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pato.png
    - assets/splash-pato.png
    - assets/googleicon.png
    - assets/gif-pato.gif
    - assets/pato-triste.png
    - assets/patodeoculos.png
    - assets/jon_profile.png
    - assets/icons/add_task_icon.svg
