// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7H1ELWrRKwX72DlBiPyph55OXu63icqo',
    appId: '1:190657188583:web:741cdbe171b8925db14842',
    messagingSenderId: '190657188583',
    projectId: 'autenticacao-mega',
    authDomain: 'autenticacao-mega.firebaseapp.com',
    storageBucket: 'autenticacao-mega.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTHV4z50Zmf8e0r2bWmKBXKvZS-DKUZXU',
    appId: '1:190657188583:android:5c3425eaf92ad88bb14842',
    messagingSenderId: '190657188583',
    projectId: 'autenticacao-mega',
    storageBucket: 'autenticacao-mega.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfk_-_lpX6vC4kzR1RnU_D6rCRWH_zLZ8',
    appId: '1:190657188583:ios:2262fc9cac2b43f1b14842',
    messagingSenderId: '190657188583',
    projectId: 'autenticacao-mega',
    storageBucket: 'autenticacao-mega.firebasestorage.app',
    iosClientId:
        '190657188583-c4j081mdnsap7d618828mcikhatbmlsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileMegajrGrupo3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfk_-_lpX6vC4kzR1RnU_D6rCRWH_zLZ8',
    appId: '1:190657188583:ios:2262fc9cac2b43f1b14842',
    messagingSenderId: '190657188583',
    projectId: 'autenticacao-mega',
    storageBucket: 'autenticacao-mega.firebasestorage.app',
    iosClientId:
        '190657188583-c4j081mdnsap7d618828mcikhatbmlsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileMegajrGrupo3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7H1ELWrRKwX72DlBiPyph55OXu63icqo',
    appId: '1:190657188583:web:08be9a0a463047e0b14842',
    messagingSenderId: '190657188583',
    projectId: 'autenticacao-mega',
    authDomain: 'autenticacao-mega.firebaseapp.com',
    storageBucket: 'autenticacao-mega.firebasestorage.app',
  );
}
